version: '3.8'

volumes:
  database-data:
  media:

services:
  # Postgresql Database
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: postgresql
    env_file:
      - .env
    # Optional: Map the container port to a host port to be able to connect with a local db client 
    ports:
      - 5432:5432
    volumes:
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - database-data:/var/lib/postgresql/data

  # Frontend app (static files)
  frontend:
    image: webpack
    restart: unless-stopped
    container_name: webpack
    build: 
      context: ../../
      dockerfile: ./docker/development/frontend/Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ../../frontend:/frontend

  # Django app
  app:
    image: django
    restart: unless-stopped
    container_name: django
    build: &app
      context: ../../
      dockerfile: ./docker/development/app/Dockerfile
      args:
        media_root: ${MEDIA_ROOT}
    env_file: &env
      - .env
    depends_on:
      - database
      - frontend
    volumes: &code
      - ../../manage.py:/code/manage.py
      - ../../app:/code/app
      - ../../config:/code/config
      - ../../frontend:/code/frontend
      - media:${MEDIA_ROOT}
    ports:
      - 8000:8000
      - 8888:8888