version: '3.8'

volumes:
  magi-studio-database-data:
  magi-studio-media:

services:
  # Postgresql Database
  magi-studio-database:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: postgresql
    env_file:
      - .env
    # Optional: Map the container port to a host port to be able to connect with a local db client 
    ports:
      - 5432:5432
    volumes:
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - magi-studio-database-data:/var/lib/postgresql/data

  # Frontend app (static files)
  frontend:
    image: webpack
    restart: unless-stopped
    container_name: webpack
    build: 
      context: ../../
      dockerfile: ./docker/development/frontend/Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ../../frontend:/frontend

  # Django app
  app:
    image: django
    restart: unless-stopped
    container_name: django
    build: &app
      context: ../../
      dockerfile: ./docker/development/app/Dockerfile
      args:
        media_root: ${MEDIA_ROOT}
    env_file: &env
      - .env
    depends_on:
      - magi-studio-database
      - frontend
    volumes: &code
      - ../../:/code
      - magi-studio-media:${MEDIA_ROOT}
      - ../../.git:/code/.git
    ports:
      - 8000:8000
      - 8888:8888

  # Redis Broker
  broker:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
    depends_on:
      - magi-studio-database

  # Celery Worker
  worker:
    image: celery-worker
    restart: unless-stopped
    container_name: celery-worker
    build: *app
    command: start-celery-worker.sh
    env_file: *env
    volumes: *code
    depends_on:
      - magi-studio-database
      - broker
      - app

  git-hooks:
    container_name: git-hooks
    build:
      context: ../../
      dockerfile: ./docker/development/git-hooks/Dockerfile
    volumes:
      - ../../.git:/tmp/.git
      - ../../hooks:/tmp/hooks
