version: '3.8'

volumes:
  magi-studio-database-data:
  magi-studio-static:
  magi-studio-media:

services:
  # Postgresql Database
  magi-studio-database:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: magi-studio-database
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - magi-studio-database-data:/var/lib/postgresql/data

  # Django app
  magi-studio-app:
    image: spetiot/magi-studio:latest
    container_name: magi-studio-app
    env_file: &env
      - .env
    volumes: &vol
      - /var/www/static/magi-studio/:${STATIC_ROOT}:rw
      - /var/www/media/magi-studio/:${MEDIA_ROOT}:rw

  # Gunicorn WSGI server
  magi-studio-wsgi:
    image: spetiot/magi-studio:latest
    command: start-gunicorn-server.sh
    restart: unless-stopped
    container_name:  magi-studio-wsgi
    env_file: *env
    volumes: *vol
    depends_on:
      -  magi-studio-app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    
  # Daphne ASGI server
  magi-studio-asgi:
    image: spetiot/magi-studio:latest
    command: start-daphne-server.sh
    restart: unless-stopped
    container_name: magi-studio-asgi
    env_file: *env
    volumes: *vol
    depends_on:
      - magi-studio-app
    ports:
      - "8001:8001"
    expose:
      - "8001"

  # Redis Broker
  magi-studio-broker:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: magi-studio-broker
    ports:
      - "6379"

  # Celery Worker
  magi-studio-worker:
    image: spetiot/magi-studio:latest
    command: start-celery-worker.sh
    restart: unless-stopped
    container_name: magi-studio-worker
    env_file: *env
    volumes: *vol
    depends_on:
      - magi-studio-broker
      - magi-studio-app